# Generated by Django 5.2.4 on 2025-07-23 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_intro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('profile_update', 'Profile Update'), ('family_member_added', 'Family Member Added'), ('connection_made', 'Connection Made'), ('featured_family_update', 'Featured Family Update'), ('community_event', 'Community Event')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='acc_intro.newpersonalprofile')),
            ],
            options={
                'verbose_name_plural': 'Community Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_since', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(help_text='Why this family is featured')),
                ('priority_level', models.IntegerField(default=1, help_text='Higher number = higher priority')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured_family', to='acc_intro.newpersonalprofile')),
            ],
            options={
                'ordering': ['-priority_level', '-featured_since'],
            },
        ),
        migrations.CreateModel(
            name='FamilyConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message when requesting connection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_sent', to='acc_intro.newpersonalprofile')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_received', to='acc_intro.newpersonalprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('initiator', 'receiver')},
            },
        ),
    ]
