# Generated by Django 5.2.4 on 2025-11-18 06:55

from django.db import migrations, models


def add_password_change_required_column(apps, schema_editor):
    table_name = 'acc_intro_newpersonalprofile'
    column_name = 'password_change_required'

    with schema_editor.connection.cursor() as cursor:
        columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor, table_name
            )
        }

    if column_name not in columns:
        model = apps.get_model('acc_intro', 'NewPersonalProfile')
        field = models.BooleanField(
            default=False,
            help_text='Require user to change their password on next login',
        )
        field.set_attributes_from_name(column_name)
        schema_editor.add_field(model, field)

    quoted_table = schema_editor.quote_name(table_name)
    quoted_column = schema_editor.quote_name(column_name)
    schema_editor.execute(
        f"UPDATE {quoted_table} "
        f"SET {quoted_column} = FALSE "
        f"WHERE {quoted_column} IS NULL"
    )


def remove_password_change_required_column(apps, schema_editor):
    table_name = 'acc_intro_newpersonalprofile'
    column_name = 'password_change_required'

    with schema_editor.connection.cursor() as cursor:
        columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor, table_name
            )
        }

    if column_name in columns:
        model = apps.get_model('acc_intro', 'NewPersonalProfile')
        field = models.BooleanField(
            default=False,
            help_text='Require user to change their password on next login',
        )
        field.set_attributes_from_name(column_name)
        schema_editor.remove_field(model, field)


class Migration(migrations.Migration):

    dependencies = [
        ('acc_intro', '0010_remove_unused_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_password_change_required_column,
                    remove_password_change_required_column,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='newpersonalprofile',
                    name='password_change_required',
                    field=models.BooleanField(
                        default=False,
                        help_text='Require user to change their password on next login',
                    ),
                )
            ],
        ),
    ]
