# Generated by Django 5.2.4 on 2025-11-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_intro', '0011_newpersonalprofile_password_change_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyevent',
            name='visible_to_all',
            field=models.BooleanField(default=False),
        ),
    ]
