# Generated by Django 5.2.4 on 2025-11-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_intro', '0013_add_missing_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='newfamilymember',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='newpersonalprofile',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='SharedPhoto',
        ),
    ]
