# Generated by Django 5.2.4 on 2025-11-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_intro', '0014_newfamilymember_area_newpersonalprofile_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newfamilymember',
            name='memberAge',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newfamilymember',
            name='relation',
            field=models.CharField(choices=[('spouse', 'Spouse'), ('son', 'Son'), ('daughter', 'Daughter'), ('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('cousin', 'Cousin'), ('nephew', 'Nephew'), ('niece', 'Niece'), ('son_in_law', 'Son-in-law'), ('daughter_in_law', 'Daughter-in-law'), ('father_in_law', 'Father-in-law'), ('mother_in_law', 'Mother-in-law'), ('grandson', 'Grandson'), ('granddaughter', 'Granddaughter'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='newpersonalprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
