# Generated by Django 5.2.4 on 2025-11-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_intro', '0015_alter_newfamilymember_memberage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newfamilymember',
            name='maritalStatus',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('unmarried', 'Unmarried'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='newpersonalprofile',
            name='maritalStatus',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('unmarried', 'Unmarried'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20),
        ),
    ]
